// AUTO-GENERATED by scripts/build-registry-meta.mjs
// Do not edit manually. Run the script after modifying registry/index.ts

export interface RegistryMetaItem {
  /** Display name of the component demo */
  name: string
  /** Asset type */
  type?: "react" | "video" | "image"
  /** Render mode */
  renderMode?: "direct" | "iframe"
  /** URL to the isolated preview page */
  previewUrl?: string
  /** CLI install command */
  installCommand?: string
  /** URL to media asset */
  mediaUrl?: string
}

export const registryMeta: Record<string, RegistryMetaItem> = {
  "dashboard-pro-desktop": {
    name: "Desktop Layout",
    type: "video",
    previewUrl: "/preview/dashboard-pro/desktop",
    mediaUrl: "/videos/dashboard-desktop-preview.mp4",
  },

  "dashboard-pro-mobile": {
    name: "Mobile Layout",
    type: "image",
    previewUrl: "/preview/dashboard-pro/mobile",
    mediaUrl: "/images/dashboard-mobile-preview.webp",
  },

  "velocity-strips-image": {
    name: "Velocity Strips Image",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/velocity-strips-image",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-strips-image.json",
  },

  "velocity-strips-video": {
    name: "Velocity Strips Video",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/velocity-strips-video",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-strips-video.json",
  },

  "velocity-grid-image": {
    name: "Velocity Grid Image",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/velocity-grid-image",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-grid-image.json",
  },

  "velocity-grid-video": {
    name: "Velocity Grid Video",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/velocity-grid-video",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-grid-video.json",
  },

  "proximity-grid-image": {
    name: "Proximity Grid Image",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/proximity-grid-image",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/proximity-grid-image.json",
  },

  "proximity-grid-video": {
    name: "Proximity Grid Video",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/proximity-grid-video",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/proximity-grid-video.json",
  },

  "liquid-marble-image": {
    name: "Liquid Marble Image",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/liquid-marble-image",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/liquid-marble-image.json",
  },

  "liquid-marble-video": {
    name: "Liquid Marble Video",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/liquid-marble-video",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/liquid-marble-video.json",
  },

  "glass-slices-image": {
    name: "Glass Slices Image",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/glass-slices-image",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/glass-slices-image.json",
  },

  "glass-slices-video": {
    name: "Glass Slices Video",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/glass-slices-video",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/glass-slices-video.json",
  },

  "depth-trail-avatars-demo": {
    name: "Depth Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/depth-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/depth-trail-avatars-demo.json",
  },

  "depth-trail-images-demo": {
    name: "Depth Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/depth-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/depth-trail-images-demo.json",
  },

  "scatter-trail-avatars-demo": {
    name: "Scatter Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/scatter-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/scatter-trail-avatars-demo.json",
  },

  "scatter-trail-images-demo": {
    name: "Scatter Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/scatter-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/scatter-trail-images-demo.json",
  },

  "wind-trail-avatars-demo": {
    name: "Wind Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/wind-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/wind-trail-avatars-demo.json",
  },

  "wind-trail-images-demo": {
    name: "Wind Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/wind-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/wind-trail-images-demo.json",
  },

  "kaleidoscope-trail-avatars-demo": {
    name: "Kaleidoscope Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/kaleidoscope-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/kaleidoscope-trail-avatars-demo.json",
  },

  "kaleidoscope-trail-images-demo": {
    name: "Kaleidoscope Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/kaleidoscope-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/kaleidoscope-trail-images-demo.json",
  },

  "squircle-trail-avatars-demo": {
    name: "Squircle Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/squircle-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/squircle-trail-avatars-demo.json",
  },

  "squircle-trail-images-demo": {
    name: "Squircle Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/squircle-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/squircle-trail-images-demo.json",
  },

  "pendulum-trail-avatars-demo": {
    name: "Pendulum Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/pendulum-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/pendulum-trail-avatars-demo.json",
  },

  "pendulum-trail-images-demo": {
    name: "Pendulum Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/pendulum-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/pendulum-trail-images-demo.json",
  },

  "slinky-trail-avatars-demo": {
    name: "Slinky Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/slinky-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/slinky-trail-avatars-demo.json",
  },

  "slinky-trail-images-demo": {
    name: "Slinky Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/slinky-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/slinky-trail-images-demo.json",
  },

  "velocity-trail-avatars-demo": {
    name: "Velocity Trail Avatars Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/velocity-trail-avatars-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-trail-avatars-demo.json",
  },

  "velocity-trail-images-demo": {
    name: "Velocity Trail Images Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/velocity-trail-images-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-trail-images-demo.json",
  },

  "editorial-reveal-demo": {
    name: "Editorial Reveal Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/editorial-reveal-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/editorial-reveal-demo.json",
  },

  "elastic-pop-headline-demo": {
    name: "Elastic Pop Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/elastic-pop-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/elastic-pop-headline-demo.json",
  },

  "elastic-pop-paragraph-demo": {
    name: "Elastic Pop Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/elastic-pop-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/elastic-pop-paragraph-demo.json",
  },

  "elastic-typewriter-headline-demo": {
    name: "Elastic Typewriter Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/elastic-typewriter-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/elastic-typewriter-headline-demo.json",
  },

  "elastic-typewriter-paragraph-demo": {
    name: "Elastic Typewriter Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/elastic-typewriter-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/elastic-typewriter-paragraph-demo.json",
  },

  "flip-3d-headline-demo": {
    name: "Flip 3D Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/flip-3d-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/flip-3d-headline-demo.json",
  },

  "flip-3d-paragraph-demo": {
    name: "Flip 3D Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/flip-3d-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/flip-3d-paragraph-demo.json",
  },

  "flip-vertical-headline-demo": {
    name: "Flip Vertical Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/flip-vertical-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/flip-vertical-headline-demo.json",
  },

  "flip-vertical-paragraph-demo": {
    name: "Flip Vertical Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/flip-vertical-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/flip-vertical-paragraph-demo.json",
  },

  "fluid-ink-headline-demo": {
    name: "Fluid Ink Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/fluid-ink-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/fluid-ink-headline-demo.json",
  },

  "fluid-ink-paragraph-demo": {
    name: "Fluid Ink Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/fluid-ink-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/fluid-ink-paragraph-demo.json",
  },

  "blur-reveal-headline-demo": {
    name: "Blur Reveal Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/blur-reveal-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/blur-reveal-headline-demo.json",
  },

  "blur-reveal-paragraph-demo": {
    name: "Blur Reveal Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/blur-reveal-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/blur-reveal-paragraph-demo.json",
  },

  "fluid-typewriter-headline-demo": {
    name: "Fluid Typewriter Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/fluid-typewriter-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/fluid-typewriter-headline-demo.json",
  },

  "fluid-typewriter-paragraph-demo": {
    name: "Fluid Typewriter Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/fluid-typewriter-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/fluid-typewriter-paragraph-demo.json",
  },

  "granular-dust-headline-demo": {
    name: "Granular Dust Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/granular-dust-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/granular-dust-headline-demo.json",
  },

  "granular-dust-paragraph-demo": {
    name: "Granular Dust Paragraph Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/granular-dust-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/granular-dust-paragraph-demo.json",
  },

  "heat-mirage-headline-demo": {
    name: "Heat Mirage Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/heat-mirage-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/heat-mirage-headline-demo.json",
  },

  "heat-mirage-paragraph-demo": {
    name: "Heat Mirage Paragraph Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/heat-mirage-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/heat-mirage-paragraph-demo.json",
  },

  "liquid-mercury-headline-demo": {
    name: "Liquid Mercury Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/liquid-mercury-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/liquid-mercury-headline-demo.json",
  },

  "magnetic-snap-demo": {
    name: "Magnetic Snap Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/magnetic-snap-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/magnetic-snap-demo.json",
  },

  "manifesto-text-reveal-demo": {
    name: "Manifesto Text Reveal Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/manifesto-text-reveal-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/manifesto-text-reveal-demo.json",
  },

  "masked-reveal-headline-demo": {
    name: "Masked Reveal Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/masked-reveal-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/masked-reveal-headline-demo.json",
  },

  "masked-reveal-paragraph-demo": {
    name: "Masked Reveal Paragraph Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/masked-reveal-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/masked-reveal-paragraph-demo.json",
  },

  "fold-reveal-demo": {
    name: "Fold Reveal Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/fold-reveal-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/fold-reveal-demo.json",
  },

  "pendulum-reveal-demo": {
    name: "Pendulum Reveal Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/pendulum-reveal-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/pendulum-reveal-demo.json",
  },

  "piano-typewriter-demo": {
    name: "Piano Typewriter Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/piano-typewriter-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/piano-typewriter-demo.json",
  },

  "multi-color-trail-char-demo": {
    name: "Multi-Color Trail Char Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/multi-color-trail-char-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/multi-color-trail-char-demo.json",
  },

  "multi-color-trail-word-demo": {
    name: "Multi-Color Trail Word Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/multi-color-trail-word-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/multi-color-trail-word-demo.json",
  },

  "multi-color-trail-line-demo": {
    name: "Multi-Color Trail Line Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/multi-color-trail-line-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/multi-color-trail-line-demo.json",
  },

  "tumbler-roll-reveal-demo": {
    name: "Tumbler Roll Reveal Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/tumbler-roll-reveal-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/tumbler-roll-reveal-demo.json",
  },

  "bottom-hinge-text-reveal-demo": {
    name: "Bottom Hinge Text Reveal Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/bottom-hinge-text-reveal-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/bottom-hinge-text-reveal-demo.json",
  },

  "velocity-brake-demo": {
    name: "Velocity Brake Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/velocity-brake-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/velocity-brake-demo.json",
  },

  "weightless-float-headline-demo": {
    name: "Weightless Float Headline Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/weightless-float-headline-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/weightless-float-headline-demo.json",
  },

  "weightless-float-paragraph-demo": {
    name: "Weightless Float Paragraph Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/weightless-float-paragraph-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/weightless-float-paragraph-demo.json",
  },

  "wind-shear-char-demo": {
    name: "Wind Shear Character Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/wind-shear-char-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/wind-shear-char-demo.json",
  },

  "wind-shear-word-demo": {
    name: "Wind Shear Word Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/wind-shear-word-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/wind-shear-word-demo.json",
  },

  "z-axis-char-demo": {
    name: "Z-Axis Character Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/z-axis-char-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/z-axis-char-demo.json",
  },

  "z-axis-word-demo": {
    name: "Z-Axis Word Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/z-axis-word-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/z-axis-word-demo.json",
  },

  "concave-carousel-demo": {
    name: "Concave Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/concave-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/concave-carousel-demo.json",
  },

  "ascent-carousel-demo": {
    name: "Ascent Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/ascent-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/ascent-carousel-demo.json",
  },

  "wave-carousel-demo": {
    name: "Wave Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/wave-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/wave-carousel-demo.json",
  },

  "convex-carousel-demo": {
    name: "Convex Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/convex-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/convex-carousel-demo.json",
  },

  "ember-burn-demo": {
    name: "Ember Burn Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/ember-burn-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/ember-burn-demo.json",
  },

  "ferrofluid-drag-demo": {
    name: "Ferrofluid Drag Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/ferrofluid-drag-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/ferrofluid-drag-demo.json",
  },

  "fluid-disintegration-demo": {
    name: "Fluid Disintegration Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/fluid-disintegration-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/fluid-disintegration-demo.json",
  },

  "liquid-curtain-demo": {
    name: "Liquid Curtain Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/liquid-curtain-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/liquid-curtain-demo.json",
  },

  "mycelium-network-demo": {
    name: "Mycelium Network Demo",
    type: "react",
    renderMode: "direct",
    previewUrl: "/preview/mycelium-network-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/mycelium-network-demo.json",
  },

  "dimensional-deck-demo": {
    name: "Dimensional Deck Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/dimensional-deck-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/dimensional-deck-demo.json",
  },

  "dimensional-carousel-demo": {
    name: "Dimensional Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/dimensional-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/dimensional-carousel-demo.json",
  },

  "panoramic-carousel-demo": {
    name: "Panoramic Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/panoramic-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/panoramic-carousel-demo.json",
  },

  "flex-carousel-demo": {
    name: "Flex Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/flex-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/flex-carousel-demo.json",
  },

  "depth-carousel-demo": {
    name: "Depth Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/depth-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/depth-carousel-demo.json",
  },

  "cover-carousel-demo": {
    name: "Cover Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/cover-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/cover-carousel-demo.json",
  },

  "curved-carousel-demo": {
    name: "Curved Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/curved-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/curved-carousel-demo.json",
  },

  "elastic-carousel-demo": {
    name: "Elastic Carousel Demo",
    type: "react",
    renderMode: "iframe",
    previewUrl: "/preview/elastic-carousel-demo",
    installCommand: "npx shadcn@latest add https://ui.satisium.com/r/elastic-carousel-demo.json",
  },

}
