// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"blocks/ao.mdx": () => import("../content/docs/blocks/ao.mdx?collection=docs"), "blocks/aurora-hero.mdx": () => import("../content/docs/blocks/aurora-hero.mdx?collection=docs"), "blocks/button.mdx": () => import("../content/docs/blocks/button.mdx?collection=docs"), "blocks/fluid-switch.mdx": () => import("../content/docs/blocks/fluid-switch.mdx?collection=docs"), "blocks/spotlight-card.mdx": () => import("../content/docs/blocks/spotlight-card.mdx?collection=docs"), "components/ao.mdx": () => import("../content/docs/components/ao.mdx?collection=docs"), "components/aurora-hero.mdx": () => import("../content/docs/components/aurora-hero.mdx?collection=docs"), "components/fluid-switch.mdx": () => import("../content/docs/components/fluid-switch.mdx?collection=docs"), "components/index.mdx": () => import("../content/docs/components/index.mdx?collection=docs"), "components/magnetic-button.mdx": () => import("../content/docs/components/magnetic-button.mdx?collection=docs"), "components/spotlight-card.mdx": () => import("../content/docs/components/spotlight-card.mdx?collection=docs"), "getting-started/changelog.mdx": () => import("../content/docs/getting-started/changelog.mdx?collection=docs"), "getting-started/how-to-use.mdx": () => import("../content/docs/getting-started/how-to-use.mdx?collection=docs"), "getting-started/introduction.mdx": () => import("../content/docs/getting-started/introduction.mdx?collection=docs"), "getting-started/setup.mdx": () => import("../content/docs/getting-started/setup.mdx?collection=docs"), "templates/ao.mdx": () => import("../content/docs/templates/ao.mdx?collection=docs"), "templates/aurora-hero.mdx": () => import("../content/docs/templates/aurora-hero.mdx?collection=docs"), "templates/button.mdx": () => import("../content/docs/templates/button.mdx?collection=docs"), "templates/fluid-switch.mdx": () => import("../content/docs/templates/fluid-switch.mdx?collection=docs"), "templates/spotlight-card.mdx": () => import("../content/docs/templates/spotlight-card.mdx?collection=docs"), }),
};
export default browserCollections;