// @ts-nocheck
import * as __fd_glob_44 from "../content/docs/templates/spotlight-card.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/templates/fluid-switch.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/templates/button.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/templates/aurora-hero.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/templates/ao.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/getting-started/setup.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/getting-started/introduction.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/getting-started/how-to-use.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/getting-started/changelog.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/wind-trail.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/velocity-trail.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/velocity-strips.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/velocity-grid.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/squircle-trail.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/slinky-trail.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/scatter-trail.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/proximity-grid.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/pendulum-trail.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/liquid-marble.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/kaleidoscope-trail.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/halftone-video-horizontal.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/halftone-video-hero.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/halftone-horizontal.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/halftone-hero.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/glass-slices.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/fluid-ink-reveal.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/flip-vertical-reveal.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/flip-3d-reveal.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/elastic-typewriter.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/elastic-pop-reveal.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/editorial-reveal.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/depth-trail.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/bouquet-trail.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/blocks/spotlight-card.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/blocks/fluid-switch.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/blocks/e-commerce-dashboard.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/blocks/button.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/blocks/aurora-hero.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/blocks/ao.mdx?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/templates/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/blocks/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "blocks/meta.json": __fd_glob_1, "components/meta.json": __fd_glob_2, "getting-started/meta.json": __fd_glob_3, "templates/meta.json": __fd_glob_4, }, {"blocks/ao.mdx": __fd_glob_5, "blocks/aurora-hero.mdx": __fd_glob_6, "blocks/button.mdx": __fd_glob_7, "blocks/e-commerce-dashboard.mdx": __fd_glob_8, "blocks/fluid-switch.mdx": __fd_glob_9, "blocks/spotlight-card.mdx": __fd_glob_10, "components/bouquet-trail.mdx": __fd_glob_11, "components/depth-trail.mdx": __fd_glob_12, "components/editorial-reveal.mdx": __fd_glob_13, "components/elastic-pop-reveal.mdx": __fd_glob_14, "components/elastic-typewriter.mdx": __fd_glob_15, "components/flip-3d-reveal.mdx": __fd_glob_16, "components/flip-vertical-reveal.mdx": __fd_glob_17, "components/fluid-ink-reveal.mdx": __fd_glob_18, "components/glass-slices.mdx": __fd_glob_19, "components/halftone-hero.mdx": __fd_glob_20, "components/halftone-horizontal.mdx": __fd_glob_21, "components/halftone-video-hero.mdx": __fd_glob_22, "components/halftone-video-horizontal.mdx": __fd_glob_23, "components/index.mdx": __fd_glob_24, "components/kaleidoscope-trail.mdx": __fd_glob_25, "components/liquid-marble.mdx": __fd_glob_26, "components/pendulum-trail.mdx": __fd_glob_27, "components/proximity-grid.mdx": __fd_glob_28, "components/scatter-trail.mdx": __fd_glob_29, "components/slinky-trail.mdx": __fd_glob_30, "components/squircle-trail.mdx": __fd_glob_31, "components/velocity-grid.mdx": __fd_glob_32, "components/velocity-strips.mdx": __fd_glob_33, "components/velocity-trail.mdx": __fd_glob_34, "components/wind-trail.mdx": __fd_glob_35, "getting-started/changelog.mdx": __fd_glob_36, "getting-started/how-to-use.mdx": __fd_glob_37, "getting-started/introduction.mdx": __fd_glob_38, "getting-started/setup.mdx": __fd_glob_39, "templates/ao.mdx": __fd_glob_40, "templates/aurora-hero.mdx": __fd_glob_41, "templates/button.mdx": __fd_glob_42, "templates/fluid-switch.mdx": __fd_glob_43, "templates/spotlight-card.mdx": __fd_glob_44, });