// @ts-nocheck
import * as __fd_glob_74 from "../content/docs/templates/spotlight-card.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/templates/fluid-switch.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/templates/button.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/templates/aurora-hero.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/templates/ao.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/getting-started/setup.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/getting-started/introduction.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/getting-started/how-to-use.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/getting-started/changelog.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/components/z-axis-reveal.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/components/wind-trail.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/components/wind-shear-reveal.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/components/weightless-float-reveal.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/components/wave-carousel.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/components/velocity-trail.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/components/velocity-strips.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/components/velocity-grid.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/components/velocity-brake-reveal.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/components/tumbler-roll-reveal.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/components/squircle-trail.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/components/slinky-trail.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/components/scatter-trail.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/components/proximity-grid.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/components/piano-typewriter.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/components/pendulum-trail.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/components/pendulum-reveal.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/components/mycelium-network.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/multi-color-trail-reveal.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/masked-reveal.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/manifesto-text-reveal.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/magnetic-snap-reveal.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/liquid-mercury-reveal.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/liquid-marble.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/liquid-curtain.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/kaleidoscope-trail.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/index.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/heat-mirage-reveal.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/halftone-video-horizontal.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/halftone-video-hero.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/halftone-horizontal.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/halftone-hero.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/granular-dust-reveal.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/glass-slices.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/fold-reveal.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/fluid-typewriter.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/fluid-ink-reveal.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/fluid-disintegration.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/flip-vertical-reveal.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/flip-3d-reveal.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/ferrofluid-drag.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/exponential-carousel.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/ember-burn.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/elastic-typewriter.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/elastic-pop-reveal.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/editorial-reveal.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/dimensional-deck.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/dimensional-carousel.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/depth-trail.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/convex-carousel.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/concave-carousel.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/bouquet-trail.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/bottom-hinge-text-reveal.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/blur-reveal.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/ascent-carousel.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/blocks/spotlight-card.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/blocks/fluid-switch.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/blocks/e-commerce-dashboard.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/blocks/button.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/blocks/aurora-hero.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/blocks/ao.mdx?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/templates/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/blocks/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "blocks/meta.json": __fd_glob_1, "components/meta.json": __fd_glob_2, "getting-started/meta.json": __fd_glob_3, "templates/meta.json": __fd_glob_4, }, {"blocks/ao.mdx": __fd_glob_5, "blocks/aurora-hero.mdx": __fd_glob_6, "blocks/button.mdx": __fd_glob_7, "blocks/e-commerce-dashboard.mdx": __fd_glob_8, "blocks/fluid-switch.mdx": __fd_glob_9, "blocks/spotlight-card.mdx": __fd_glob_10, "components/ascent-carousel.mdx": __fd_glob_11, "components/blur-reveal.mdx": __fd_glob_12, "components/bottom-hinge-text-reveal.mdx": __fd_glob_13, "components/bouquet-trail.mdx": __fd_glob_14, "components/concave-carousel.mdx": __fd_glob_15, "components/convex-carousel.mdx": __fd_glob_16, "components/depth-trail.mdx": __fd_glob_17, "components/dimensional-carousel.mdx": __fd_glob_18, "components/dimensional-deck.mdx": __fd_glob_19, "components/editorial-reveal.mdx": __fd_glob_20, "components/elastic-pop-reveal.mdx": __fd_glob_21, "components/elastic-typewriter.mdx": __fd_glob_22, "components/ember-burn.mdx": __fd_glob_23, "components/exponential-carousel.mdx": __fd_glob_24, "components/ferrofluid-drag.mdx": __fd_glob_25, "components/flip-3d-reveal.mdx": __fd_glob_26, "components/flip-vertical-reveal.mdx": __fd_glob_27, "components/fluid-disintegration.mdx": __fd_glob_28, "components/fluid-ink-reveal.mdx": __fd_glob_29, "components/fluid-typewriter.mdx": __fd_glob_30, "components/fold-reveal.mdx": __fd_glob_31, "components/glass-slices.mdx": __fd_glob_32, "components/granular-dust-reveal.mdx": __fd_glob_33, "components/halftone-hero.mdx": __fd_glob_34, "components/halftone-horizontal.mdx": __fd_glob_35, "components/halftone-video-hero.mdx": __fd_glob_36, "components/halftone-video-horizontal.mdx": __fd_glob_37, "components/heat-mirage-reveal.mdx": __fd_glob_38, "components/index.mdx": __fd_glob_39, "components/kaleidoscope-trail.mdx": __fd_glob_40, "components/liquid-curtain.mdx": __fd_glob_41, "components/liquid-marble.mdx": __fd_glob_42, "components/liquid-mercury-reveal.mdx": __fd_glob_43, "components/magnetic-snap-reveal.mdx": __fd_glob_44, "components/manifesto-text-reveal.mdx": __fd_glob_45, "components/masked-reveal.mdx": __fd_glob_46, "components/multi-color-trail-reveal.mdx": __fd_glob_47, "components/mycelium-network.mdx": __fd_glob_48, "components/pendulum-reveal.mdx": __fd_glob_49, "components/pendulum-trail.mdx": __fd_glob_50, "components/piano-typewriter.mdx": __fd_glob_51, "components/proximity-grid.mdx": __fd_glob_52, "components/scatter-trail.mdx": __fd_glob_53, "components/slinky-trail.mdx": __fd_glob_54, "components/squircle-trail.mdx": __fd_glob_55, "components/tumbler-roll-reveal.mdx": __fd_glob_56, "components/velocity-brake-reveal.mdx": __fd_glob_57, "components/velocity-grid.mdx": __fd_glob_58, "components/velocity-strips.mdx": __fd_glob_59, "components/velocity-trail.mdx": __fd_glob_60, "components/wave-carousel.mdx": __fd_glob_61, "components/weightless-float-reveal.mdx": __fd_glob_62, "components/wind-shear-reveal.mdx": __fd_glob_63, "components/wind-trail.mdx": __fd_glob_64, "components/z-axis-reveal.mdx": __fd_glob_65, "getting-started/changelog.mdx": __fd_glob_66, "getting-started/how-to-use.mdx": __fd_glob_67, "getting-started/introduction.mdx": __fd_glob_68, "getting-started/setup.mdx": __fd_glob_69, "templates/ao.mdx": __fd_glob_70, "templates/aurora-hero.mdx": __fd_glob_71, "templates/button.mdx": __fd_glob_72, "templates/fluid-switch.mdx": __fd_glob_73, "templates/spotlight-card.mdx": __fd_glob_74, });