// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mjs
// Do not edit this file directly.
import dynamic from "next/dynamic";

export const Index: Record<string, any> = {
  "spotlight-card": {
    name: "spotlight-card",
    type: "registry:ui",
    registryDependencies: [],
    component: dynamic(() => import("@/registry/default/ui/spotlight-card")),
    raw: `"use client"

import React, { useRef, MouseEvent } from "react"
import { motion, useMotionTemplate, useMotionValue } from "motion/react"
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

// Standard Shadcn utility (usually in lib/utils.ts)
function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export interface SpotlightCardProps extends React.HTMLAttributes<HTMLDivElement> {
  glowColor?: string
  glowRadius?: number
}

export function SpotlightCard({
  children,
  className,
  glowColor = "rgba(255, 255, 255, 0.08)", // Subtle white glow for dark mode
  glowRadius = 300,
  ...props
}: SpotlightCardProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mouseX = useMotionValue(-glowRadius) // Start safely off-screen
  const mouseY = useMotionValue(-glowRadius)

  function handleMouseMove({ clientX, clientY }: MouseEvent<HTMLDivElement>) {
    if (!containerRef.current) return
    const { left, top } = containerRef.current.getBoundingClientRect()
    // Calculate mouse position relative to the card
    mouseX.set(clientX - left)
    mouseY.set(clientY - top)
  }

  return (
    <div
      ref={containerRef}
      onMouseMove={handleMouseMove}
      className={cn(
        "group relative overflow-hidden rounded-3xl border border-border bg-card shadow-sm transition-shadow duration-300 hover:shadow-md",
        className
      )}
      {...props}
    >
      {/* The Dynamic Spotlight Overlay */}
      <motion.div
        className="pointer-events-none absolute inset-0 z-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100"
        style={{
          background: useMotionTemplate\`
            radial-gradient(
              \${glowRadius}px circle at \${mouseX}px \${mouseY}px,
              \${glowColor},
              transparent 80%
            )
          \`,
        }}
      />
      {/* The Content */}
      <div className="relative z-10 h-full w-full">{children}</div>
    </div>
  )
}
`,
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    type: "registry:example",
    registryDependencies: ["spotlight-card"],
    component: dynamic(() => import("@/registry/default/demos/spotlight-card-demo")),
    raw: `"use client"

import { SpotlightCard } from "@/registry/default/ui/spotlight-card"

export default function SpotlightCardDemo({
  glowColor = "rgba(255, 255, 255, 0.1)",
  glowRadius = 350,
}: {
  glowColor?: string
  glowRadius?: number
}) {
  return (
    <div className="flex w-full items-center justify-center p-8 md:p-12">
      <SpotlightCard
        glowColor={glowColor}
        glowRadius={glowRadius}
        className="flex min-h-[320px] w-full max-w-[400px] flex-col justify-between p-8"
      >
        <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-border/50 bg-background/50 shadow-inner">
          <span className="text-xl">✨</span>
        </div>

        <div className="mt-12">
          <h3 className="font-heading text-2xl font-bold tracking-tight text-foreground">
            Spatial Awareness.
          </h3>
          <p className="mt-4 font-body leading-relaxed text-muted-foreground">
            We orchestrate the DOM. We don't just put things in boxes; we
            respect the physical laws of the digital canvas.
          </p>
        </div>
      </SpotlightCard>
    </div>
  )
}
`,
  },
};
